[workspace]
resolver = "2"
members = ["rsdex_main"]

[workspace.dependencies]
serde = {version = "1.0.228",features = ["derive"]}
serde_json = "1.0.149"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
