[package]
name = "rsdex"
version = "0.1.0"
edition = "2024"
description = "a little tool that behaves like the pokedex"
license = "MIT"
repository = "https://github.com/PurpleCraft999/rsdex"


[dependencies]
rayon = "1.11.0"
serde_json = "1.0.149"
serde = {version = "1.0.228",features = ["derive"]}
clap = { version = "4.5.54", features = ["derive"] }
strum = { version = "0.27.2", features = ["derive"] }
memmap2 = "0.9.9"
strsim = "0.11.1"

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
