[package]
name = "rsdex_main"
license = "MIT"
edition = "2024"
version = "0.1.70"

repository = "https://github.com/PurpleCraft999/rsdex"
authors = ["PurpleCraft999"]
readme = "../README.md"
[package.metadata.dist]
dist = true




[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
rsdex_lib = { path = "../../rsdex/rsdex_lib"}