[package]
name = "rsdex_main"
license = "MIT"
edition = "2024"
version.workspace = true
repository.workspace = true
authors = ["PurpleCraft999"]
readme = "../README.md"





[package.metadata.dist]
dist = true




[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
rsdex_lib = { path = "../../rsdex/rsdex_lib/"}


