[package]
name = "rsdex_main"
license = "MIT"
edition.workspace = true
version.workspace = true
repository.workspace = true
authors = ["PurpleCraft999"]
readme.workspace = true





[package.metadata.dist]
dist = true




[dependencies]
clap = { version = "4.5.54", features = ["derive"] }
rsdex_lib = { path = "../../rsdex/rsdex_lib/"}


